<?php

define('DIR_LIB', __DIR__ . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR);
define('DIR_CONTROLLERS', __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR .'controllers' . DIRECTORY_SEPARATOR);
define('DIR_MODELS', __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR .'models' . DIRECTORY_SEPARATOR);
define('DIR_VIEWS', __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR .'views' . DIRECTORY_SEPARATOR);
define('DIR_CONFIG', __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR .'config' . DIRECTORY_SEPARATOR);
